AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Posting plack message'
Resources:
  PostSlack:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          SLACK_TOKEN: !Ref SlackToken
          SLACK_CHANEL: !Ref SlackChanel
          SLACK_CHANEL_DEV: !Ref SlackChanelDev
          STAGE: !Ref Stage
  IncommingWebHook:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.incommingHandler
      Runtime: nodejs8.10
      Environment:
        Variables:
          SLACK_CHANEL: !Ref SlackChanel
          SLACK_CHANEL_DEV: !Ref SlackChanelDev
          SLACK_PATH: !Ref SlackPath
          SLACK_USERNAME: !Ref SlackUsername
          STAGE: !Ref Stage
Parameters:
  SlackToken:
    Type: String
  SlackChanel:
    Type: String
  SlackChanelDev:
    Type: String
  SlackPath:
    Type: String
  SlackUsername:
    Type: String
  Stage:
    Type: String
